[package]
name = "BookLauncher"
version = "0.1.0"
edition = "2021"


[dependencies]
eframe = "0.30"
rfd = "0.15.4"
walkdir = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
